### ISSUE TITLE
should we remove this line?

### ISSUE THREAD

**Issue by badgeek** [8BitMixtape/ESPTINY86_Mixtape#1]
https://github.com/8BitMixtape/ESPTINY86_Mixtape/blob/fcc86bc7b03cfe350a6237c51228f09ab904cb31/code/022_BBC_NeoPixelSound/ESP_neolib.cpp#L51

**Comment by ChrisMicro** [comment]
Yes, you are right. It's a remnant of old code.

**Comment by ChrisMicro** [comment]
I just removed and pushed it.
